credentials:
  usernames:
    admin:
      email: henrique.filho@secti.gov.df.br
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Henrique Rocha
      password: $2b$12$ky73cn.7zZl8PQJbY1oe0OYVTy4wgW23cLAuBogICkN18DoLICWfG
    davi:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Davi
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    larissa:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Larissa Hipolito
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    leonardo:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Leonardo Reisman
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    renato:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Renato Cardoso
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    uitalo:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Uitalo
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    alexandre:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Alexandre Villain
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    michelle:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Michelle Santos
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    claudia:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Claudia Lopes
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    patricia:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Patricia Aragao
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
    kissila:
      email: bob@example.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Kissila Nicolai
      password: $2b$12$.CCizVcGEMItd6RxXjwm5OsRq6NuwMfwssxmnRg5yWJ7hTT7yZSvO
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - henrique.filho@secti.gov.df.br
